---
- name: Wipe app
  tags: wipe
  when: web_app_full_wipe
  block:
    - name: Stopping docker container
      docker_compose:
        project_src: "/opt/composes/{{ image }}"
        state: absent

    - name: Deleting image of the app
      docker_image:
        name: "{{ image }}"
        state: absent

    - name: Removing compose directory
      ansible.builtin.file:
        path: "/opt/composes/{{ image }}"
        state: absent
