---
- name: Installing docker using apt
  vars:
    docker_install_compose: false
    docker_install_compose_plugin: false
  ansible.builtin.import_role:
    name: geerlingguy.docker
  tags:
    - installation
    - docker