name: Python CI

on:
  push:
    paths:
      - "app_python/**"
      - ".github/workflows/python-ci.yml"

jobs:
  python-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_python
    
    strategy:
      matrix:
        python-version: ["3.9.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      
      - name: Linting with flake 8
        run: |
          flake8 --exclude=./venv/
      
      - name: Linting with black
        run: |
          black .
        
      #- name: Testing flask app
      #  run: |
      #    pre-commit run pytest --all-files
      #  working-directory: ./app_python fsometh che